### ISSUE TITLE
EPIC | progressive web app (PWA) support

### ISSUE THREAD

**Issue by sojeri** [sojeri/howsTheWeatherSeattle#44]
## add support for PWA
I kinda want to save this like an app on my phone, so some s#$%'s required

### basic requirements for MVP

data layer
- [ ] implement service worker & simple retry logic (every 6-8 hours?)
- [ ] update fallback weather logic
- [ ] add manifest file

view layer
- [ ] add last queried weather status
- [ ] implement a sweet, sweet favicon

### stretch goals

data layer
- [ ] add cache invalidation / retry logic: query once every 4-6 hours or 30min after sunset / before sunrise, whichever comes first

view layer
- [ ] display current time (local to query location)
